### PR TITLE
Post drop design update

### PR DESCRIPTION
**Pull request by arru**
- Responsive drop done view from iPad down to 3.5"
- Tweaked color of balls and grey area according to @paulakreuger s designs
- More accurate calculation for number of balls, using visible view size (as in overlays on iPad), width instead of height, and accounting for space taken up by share/view buttons

Most of the changes are in storyboards, **please open them up and take a look**

### CODE REVIEW

**Comment by JagCesar** [comment]
@arru What should I be looking at in the storyboard file? Anything in specific?

**Comment by JagCesar** [comment]
I have no idea if this is new or not, but we're using tap gestures instead of buttons. I think we should try using UIButtons as much as possible (or custom subclasses of UIControl) for these UI elements since they give accessibility features "for free".

image

**Comment by arru** [comment]
@JagCesar 1. mostly constraints, but it's great that you found something else :) 2. I agree - however this wasn't changed by me

**Comment by JagCesar** [comment]
The attached screenshot shows a view that doesn't conform to the current chosen device. I think it would be better if it conformed to the currently chosen device, so we get a preview of how it will render on said device.

image

**Comment by arru** [comment]
@Boerworz 1. That is a good point about performance, though we should not, and I repeat not, use view size as a performance indicator. Check performance directly and decide on a cutoff by device ID.
2. I'll take a look at that,do you have a stack trace?

**Comment by arru** [comment]
@JagCesar Sounds reasonable, but again, no changes to that view in this PR. Can we collect this feedback and address it separately?

**Comment by arru** [comment]
Everything's addressed, please look again @Boerworz

**Pull request merged**
